export enum NavigationRoutes {
  MAIN_SCREEN = 'MAIN_SCREEN',
  ONBOARDING_SCREEN = 'ONBOARDING_SCREEN',
  DISTRICT_SCREEN = 'DISTRICT_SCREEN',
  ROUTE_SCREEN = 'ROUTE_SCREEN',
  ACTIVE_ROUTE_SCREEN = 'ACTIVE_ROUTE_SCREEN',
  UNLOCK_HIDDEN_ROUTES_SCREEN = 'UNLOCK_HIDDEN_ROUTES_SCREEN'
}
